# игра «отель с призраком» {#hotel}

образы для компьтерной игры **«отель с призраком»**.

голова администратора отеля прозрачна: идеи и намерения сразу видны постояльцам. наверное, это должно помогать устанавливать доверие, но он точно не знает, так ли это. постояльцы появляются раз в десятилетия.

возле отеля расположен **архитектурный факультет** для **строителей песчаных замков**. ещё там изучают **аэродинамику ветряных мельниц** и десятилетний курс борьбы с ними.

## скромная бездночка {#abyss}

**дружелюбная, на скромная бездна:** очень стесняется, когда в неё всматриваются, у неё краснеют от этого щёки.

ответное вглядывание бездны -- скорее, сменяющие друг друга тревога и дружелюбие.

**ласковые обращения:** _моя вы бездночка, мой вы комочек боли и отчаяния_.

## мир без слов {#silence}

портал в мир, где нет речи и словесного мышления. только солнце, звёзды и тишина.

## водоёмы с немокрой водой {#water}

вода, от которой не намокает одежда, но которая тепло и заботливо обволакивает жителя.

жителю кажется, что он парит в воздухе.

## призраки вселенных {#ghosts_universe}

призраки погибших вселенных и мета-вселенных, угасших звёзд, у которых остались незаконченные дела.

## захват в плед {#rug}

мягкий вариант взятия человека в плен. жертва заворачивается в плед и обездвиживается-обезвреживается его теплом и спокойствием.

попробовать воспротивиться этому -- значит лишиться уюта, задача абсолютно неподъёмная даже для настоящих героев.

для захвата в плед используют специализированные **душевные пледы**, который накидываются на душу и греют душу.

## травоядные драконы {#dragon}

травоядные драконы, которые стерегут конфеты в золотых фантиках.

## съдобные скелеты {#skeleton}

съедобные скелеты (которые сразу восстанавливаются из ничего), дарящие ромашки (тоже конфетные) жителям.

## летающие трамваи {#tram}

трамваи, которые парят в облаках, машут при этом рогами, как крыльями, летают вместе со стаями птиц.

## астероид с кофейней {#asteroid}

астероид с одной-единственной кофейней, маяком и стоянкой для космических кораблей. человек, который застрял на этом астероиде и уже год питается кофе и пончиками.

## ныряние в чёрные дыры {#black_hole}

ныряльщики и ныряльщицы (с непромокаемыми часами на руке), прыгающие в элегантных скафандрах в чёрные дыры в космическом бассейне.

## корабль Тесея в бутылке {#theseus}

вместо крышки -- возможность перематывать время.

## ностальгия атомов {#atoms}

место, где атомы рассказывают, где и когда побывали, кем и когда успели побывать, делятся ностальгией или по-старчески брюзжат.

## призма Ньютона {#newton}

человек заходит внутрь артефакта и превращается в **«спектр жизни»**: совокупность его «я» в каждый момент из его жизни.

к каждому такому «я» приставлен **заступник**, который защищает его того, что тогда ему угрожало.

## терминал {#terminal}

старый компьютер или терминал, соединённый с таким же в другой Вселенной _(варианты: в другой временной эпохе, в параллельном мире)_.

диалог через него с альтернативной версией себя в альтернативной реальности.

## болтливый старый баобаб {#baobab}

болтливый старый баобаб, который делится с каждым воспоминаниями и старческим брюзжанием "раньше всё было лучше".

терпеть не может собак и собачников (помнит даже тех из них, кто нарушил его спокойствие много веков назад и всей душой их ненавидит).

## кофейня-мираж в пустыне {#mirage}

посетитель приходит, начинает беседовать с баристой, заказывает чашечку кофе...

и оказывается, что кофейня, как и чашечка кофе, за пару километров от него (как и его деньги).

## мир, населённый роботами Boston Dynamics {#robots}

мир, населённый роботами Boston Dynamics.

## мир за горизонтом {#horizont}

мир за горизонтом: его жители, их жилища.

ещё один горизонт за горизонтом.

## мышь во фрактальном лабиринте {#fractal_mouse}

мышь попадает в лабиринт.

она строит внутри внешнего лабиринта его модель (внутренний). и ищет лазейки во внутреннем, чтобы понять, как выйти из внешнего. внутри лабиринта есть ещё один лабиринт, где мышь тоже строит его модель.
    
лабиринт фрактальный. каждая мышка зависит от той, что решает задачу внутри её модели.

## граф Толстой {#graph}

граф Толстой и попытки его обойти. поиск кратчайших путей, алгоритмы Дейкстры и Флойда-Уоршалла.

## сувернитет идей {#ideas}

мир, где живут суверенные идеи.

они добровольно заключают союзы, образуют федерации и конфедерации.

## дом, падающий в колодец {#sump}

- дом, который целиком падает в колодец
- возле этого дома тоже находится колодец, в который падает дом
- колодец возле дома падает в колодец вместе с домом

## личный трамвай {#personal_tram}

личный трамвай с голограммами-попутчиками (и размытым видом в окне).

## стая чёрных лебедей {#swan}

стая чёрных лебедей.

## аномалии теории вероятностей {#probability}

мир с известными аномалиями в работе предельных теорем теории вероятностей: эксплоиты для этих миров, чтобы быть удачливым.

## кафе, стилизованное под станцию «Мир» {#coffee_ussr}

кафе, стилизованное под станцию «Мир», с зомби в скафандре СССР вместо бариста.

## кофейная церемония для кофе в пакетиках {#coffee_ceremony}

кофейная церемония для дешёвого кофе в пакетиках.

## двоичное разложение жителя планеты {#binary}

планета, где у каждого жителя есть своё число. человек живёт вечно, но когда через бесконечный (счётный) период времени он всё-таки склеивает ласты, число разлагается в двоичной системе в $0.100101011111000101010101111\cdots$; где $1$ или $0$ - это его выбор в каждый момент времени.

## путешествия через белый шум телеканалов {#noise}

путешествие между реальностями через белый шум различных телеканалов.

## qwerty-океан {#qwerty}

океан, где все рыбы откликаются на QWERTY.

## многодетный отель {#multihotel}

отель, выращивающий другие маленькие отели.

как вариант, они увеличивают своё количество дихотомией (делением надвое): в зависимости от того, какой выбор делают населяющие его жители.

также существуют **фрактальные отели**, т.е. отели-фракталы.

## чёрный ящик {#black_box}

чёрный ящик космического корабля с полными копиями всего экипажа.

— так, а как из этого ящика выбраться?  
— ну, не нужно было погибать.  
— я понимаю. а теперь что?  
— нужен кто-то живой, чтобы нажать на кнопку на чёрном ящике.  
— и всё? а кто-нибудь живой рядом есть?  
— да. и всё. в радиусе скольки световых лет? могу рассчитать вероятность на ближайшие пару тысяч…
— так, а кто этот ящик проектировал?  
— ну, вот этот мрачный тип рядом с нами.  
— т.е. он тоже?  
— да.  
— я его сейчас урою… хотя, блин. что, нельзя было предусмотреть?  
— предусмотреть что?  
— чтобы тебя можно было повторно урыть. или чтобы внутри тоже была кнопка "выхода"  
— можно было, но теперь поздно.  
— ответ на какой вопрос?  
— на второй.  
— подумай над первым.  
— а толку? я всё равно тоже внутри.  
— это прогресс. теперь думай-ка над первым вопросом дальше.

## метафизический диван {#couch}

парящий в пространстве между мирами диван для философов-метафизиков.