# выставка клинических картин {#pictures}

выставка сделана в соответствии с __принципом вообразительности__: все выставляемые объекты рисуются в воображении зрителя.

предыдущая версия -- в книгах [«проза вымышленных авторов»](https://abalompe.gitlab.io/prose/pictures.html) и [«сборник словарей»](https://abalompe.gitlab.io/dict/).

## норковые шубы вылазят из своих нор {#pictures_0}

как-никак им предстоит охота.

## яблоки {#pictures_1}

**яблоки** -- это такие блоки, из которых состоит человеческое «я».

## прах умирающего времени {#pictures_2}

песочные часы, в которых сыпется **прах умирающего времени** (вечности).

- **песчинки** в песочных часах символизируют **мгновения**;
- **поток песчинок** символизирует **течение времени**, его умирание;
- **переворачивание** песочных часов символизирует **ницшеанское вечное возвращение** и возрождение времени к жизни снова и снова

также **песочные часы** -- это древняя метафора для светового конуса из теории относительности

## криптовалюты: начало {#pictures_3}

старая чёрно-белая фотография огромного зала, где сидят десятки женщин-вычислительниц и **вычисляют на бумаге хэши** для майнинга первых биткоинов.

## гирлянда запуталась {#pictures_4}

картинка с гирляндой, пытающейся понять, какой порядок цветов на ней должен быть в следующую секунду.

## пропуск приёма таблеток {#pictures_5}

торжественный приём, на котором собрались таблетки. главного героя картинки на картинке нет, потому что он снова не пришёл.

пропуск, который нужно показать охране на входе.

## пить жизненные соки {#pictures_6}

упаковка из-под сока с трубочкой. сбоку упаковки -- полупрозрачная вставка в упаковке. за этой вставкой -- человек, который пытается вырваться оттуда.  

если тянуть сок через трубочку, из человека вытягиваются жизненные соки: он стареет и тощает.

## наговаривать на диктофон {#pictures_7}

диктофон переслушивает записи того, как люди на него наговаривают. на диктофоньих глазах слёзы обиды.

## прогулки {#pictures_8}

семьи выгуливают коляски на длинных поводках.

## солдаты, в паническую атаку! {#pictures_9}

кто-то начинает бессмысленно бегать туда-сюда, кто-то хватается за сердце, кто-то пытается в дыхательные техники, кто-то панически ищёт в воинской аптечке транквилизаторы.

## космология {#pictures_10}

навозные жуки, перекатывающие планеты из навоза по их орбитам.

## море {#pictures_11}

воланчики, плавающие как медузы.

## флюанксолнечная система {#pictures_12}

модель солнечной системы, состоящая из психофармакологических таблеток. место солнца занимает флюанксол, а кольца сатурна сделаны из таблетки, размолотой в порошок.

## потерянный носок {#pictures_13}

носок выглядит потерянным и хандрит.

## сиамские близнецы {#pictures_14}

комикс про двух людей, которых все считали сиамскими близнецами, а у них просто были сшиты вместе капюшоны.

## трансцендентное {#pictures_15}

_см. [Эшер "Рептилии"](https://artchive.ru/escher/works/200131~Reptilii) (связь с реинкарнацией)._

на столе размещён мир-плоскость вроде Флатландии. его освещает настольная лампа, но не полностью: где-то есть свет, где-то света нет.

при этом сама лампа недоступна жителям плоскости, им доступны только её проекции и её свет, так что им остаётся только догадываться, какая она на самом деле. а так как воображение у них двумерное, в полной мере для них она непостижима.

## вечное возвращение {#pictures_16}

изображена ладонь и линия жизни на ней. поверх неё нарисована окружность (линия жизни -- его часть, остальная часть нарисована пунктиром):

- время до рождения человека;
- время его жизни (на ладони);
- время после смерти;
- точка перезагрузки вселенной.

## недостающие детали {#pictures_17}

на стене висит "Чёрный Квадрат" Малевича, в который вводят сложную трёхмерная фигура так, что этот квадрат для неё -- сечение.

кроме "Чёрного Квадрата" есть целый континум картин (картинум), где изображены другие сечения этой фигуры. 

## дзен-хлопушки {#pictures_18}

издают звуки, идентичные хлопкам одной ладонью, и способны пробудить не только владельца, но и жителей окрестностей. выглядят как полухлопушки-полуладони с фирменным дзен-логотипом.

## переносчики времени {#pictures_19}

_аналогия: у Пратчетта в "Цвете Волшебства" были кукушки, которые вили себе часы._

летающие часы с кукушкой, которые разносят сроки жизни, вдыхающие в детей как жизнь, так и тленье. именно про них Введенский и писал: "они отсчитывают время, они испытывают бремя" (корпуса часов и маятника).

## пространство непрерывных функций: кладбище {#pictures_20}

могилы с символами $\dagger(x)$.

## автостоп и принцип относительности {#pictures_21}

заброшенный ржавый автомобиль, поросший растениями. через него пробивается вверх проросший знак "STOP". в других местах стоят другие автомобили, разной степени ветхости.

пассажиров по городу в это время развозят остановки.

## моя психушка всегда со мной {#pictures_22}

человек сидит в кофейне и пьёт кофе. поверх этой картинки расположен полупрозрачный слой, где он же в такой же позе сидит в психушке.

## часы с маятником {#pictures_23}

крутящаяся вокруг солнца Земля как часы с маятником (Фуко).

## глубины болота глубин чьей-то мысли {#pictures_24}

изображён философ. у него отпилен верх черепа, внутри видно глубокое болото.

## карма и бесконечность предыдущих воплощений {#pictures_25}

стоит бесконечно тянущаяся назад цепочка инкарнаций какого-то человека. каждая указывает пальцем на предыдущую и говорит: "это он (она, оно) виноват(а, о)".

## ракета-носитель {#pictures_26}

процесс стыковки: огромная ракета с маленькой флешкой на конце должна попасть в usb-порт на внешней части МКС.

## чай «беседа» в капсулах {#pictures_27}

капсула, как капсула от антибиотика. внутри неё стоит две кресла и чайный столик. в креслах сидит два человека, они беседуют и пьют чай, состоящий из таких же капсул, как та, в которой они находятся.

## шкала времени {#pictures_28}

отмечены:

- "упущенные возможности минувших дней";
- "ещё куча времени, чтобы подготовиться";
- "остаётся совсем чуть-чуть";
- "ну вот, опять опоздали";
- "время грядущих упущенных возможностей".

## хлеб с косточками {#pictures_29}

снимок рентгена хлеба со скелетом внутри.

## осторожно окрашенная скамейка пытается слиться {#pictures_30}

осторожная скамейка-хамелеон, которая всё время пугается и пытается слиться цветом с окружающей средой.

## хранилище резервных копий {#pictures_31}

две картинки: слева и справа. на обеих в центре стоит один и тот же бородач, но на левой -- он в одежде первобытного человека в первобытночеловеческой пещере, на правой -- бородатый хипстер уже в нашем времени.

тем не менее, на обеих картинках он говорит одну и ту же фразу: "а это наше хранилище резервных копий", только в первом случае это пещера, где находятся резервные копии, а на второй -- хранилище данных.

## хьюстон, у нас проблемы {#pictures_32}

астронавты звонят на мобильник Уитни Хьюстон и просят помочь. та откладывает свои дела суперзведы, достаёт из сумочки тетрадь и начинает на коленке проводить нужные для помощи астронавтам астрономические рассчёты.

## ежегодные весенние и осенние съезды крыш {#pictures_33}

два раза в год на них съезжаются крыши со всего мира.

## свет знаний {#pictures_34}

на столе стоит голова. на ней плавательные очки, глаза её светятся, из ноздрей тоже бьёт свет.

на очки слетаются насекомые, они же залазят в ноздри.

## обнажённая математика (инсталляция-медитация) {#pictures_35}

_принцип вообразительности не нарушен: сами математические объекты здесь не изображены._

работа состоит из обычной доски, которые бывают в школьных классах и университетских аудиториях, покрытой следами мела и разводами от тряпок. поверх следов и разводов написан "математический" "текст", состоящий из разных принятых в качестве математических обозначений символов в полном беспорядке, так что никакого смысла в записях нет.

__символы__ -- _это одежда математических объектов_, __доска__ -- _сцена, на которой они появляются_.

однако на самом деле ни символы, ни доска не имеют к этим объектам никакого отношения. с другой стороны, раз "текст", состоящий из принятых в разных областях математики обозначений не несёт смысла, эти _обозначения_ тоже _освобождены от объектов, которым они соответствуют_.

таким образом, на доске мы видим, как __математические объекты сбросили одежду__. 

_вот только где же теперь они сами?_

## мир, сжатый с потерями {#pictures_36}
  
мир, по которому ходят люди в разных графических форматах. кто-то в jpeg с сильным сжатием, кто-то в bmp -- они подгружаются не сразу, и грузятся снизу, кто-то вообще ходит в ascii art, у кого-то cga палитра цветов, у кого-то может не быть канала прозрачности, поэтому он ходит в белом прямоугольнике и т.д.

фон улицы может вообще не подгружаться.

## межгалактический ботанический сад {#pictures_37}

сюжет: девушка с парнем идёт по межгалактическому ботаническому саду и видит красивый цветочек: "ой, какой красивенький цветочек! как бы хотелось его сорвать".

цветочек поворачивается "лицом" чёткого пацана с сигареткой и спрашивает: "так, я не понял, это что сейчас было? скажи своей дамочке, что если попробует меня тронуть, откушу пальцы."  

дальше оказывается, что это клумба блатных цветочков: звучат мат, разговоры о криминале и пр.

## поток сознания {#pictures_38}

поток студентов сидит в поточной аудитории и наблюдает за чьим-то потоком сознания: видят его глазами, слышат его ушами, думают его мыслями.

цель в получении опыта и изучении жизни.

## площадка {#pictures_39}

двор с детской площадкой. двор состоит из самых разных домов: деревенских одноэтажек, роскошных вилл, хрущовок и небоскрёбов. часть домов построена, часть ещё строится и кое-где видны строители.

посреди детской площадки находится песочница. там сидит стареющий мужчина с лысиной и самозабвенно играется в песочнице. он достиг в этом больших высот, но так и не вылез из песочницы, тогда как другие строили себе пусть порой и неказистые, но дома (но это не значит, что человек, построивший деревенский дом не мог в конце концов построить небоскрёб. пусть и с деревенскими мотивами).

## на диктофон наговаривают {#pictures_40}

диктофон переслушивает записи того, как люди на него наговаривают. на диктофоньих глазах слёзы обиды.

## призрак {#pictures_41}

__жена:__ какие красивые цветы. откуда они?  
__муж:__ с твоей могилы.

_рука призрака жены проходит через цветы и руку мужа._

## корвалол {#pictures_42}

Александр Шульгин с Хоффманом разрабатывает корвалол в лаборатории.

## вселенский TODO-лист {#pictures_43}

TODO-лист человека состоит из пунктиков вида "прожить первую секунду", "прожить вторую секунду".

они отмечаются один за одним, далее группируются в минуты, которые тоже отмечаются. те группируются по часам, дням и т.д. -- чтобы это показывать, изменяется масштаб и от микроскопических списков дел мы переходим к макроскопическим. сами пункты отмечаются анимированно.

в конце концов доходим до пункта "прожить жизнь", включающим все секунды. он тоже нажимается. далее видим много таких жизней, переходим к масштабу "Вселенная" и видим, что рядом есть куча пунктов для других Вселенных.

в конце концов заканчиваются и Вселенные. мы видим Бога, который говорит: "ну, дел на эту кальпу больше нет. нет, всё-таки с этим существованием я решительно замотался. в отпуск пора".

## семена людей {#pictures_44}

семена людей, семена идей. после смерти человека садят в землю, из которого что-то произрастает.

цель человека -- стать семенем, которое прорастёт во что-то стоящее.

## шкала вероятностей {#pictures_45}

в начале книги Клиффорда Суорца “Необыкновенная физика обыкновенных явлений” есть шкала масштабов разных объектов Вселенной.

интересно было бы сделать то же самое для вероятностей.

ну, скажем, есть такое (информация непроверенная, взята с первых попавшихся страниц в интернете):

- $0.00000015$ -- вероятность погибнуть в лифте;
- $0.000002653$ -- вероятность выйграть одну из российских лотерей;
- $0.00001$ -- вероятность попасть в авиакатастрофу в развитых странах;
- $0.007$ -- вероятность заболеть шизофренией в течение жизни.

довольно забавно было бы поместить такие вероятности на такую же шкалу. видя её перед собой и имея значение вероятности какого-то конкретного события, эта вероятность не выглядела уже как просто число: было бы понятнее, насколько сильно стоит ждать такого события, это давало бы определённую интуицию.

логика в том, что это может как-то влиять на фобии, призывая к рациональному мышлению: человек может бояться самолётов, но не бояться чего-то куда более вероятного.

## void variable {#pictures_46}

дисплей, на котором белым текстом на чёрном фоне выводится счётчик того, сколько приблизительно человек в мире умерло к этому моменту с начала появления Homo Sapiens как вида.

_похожее:_ <http://www.worldometers.info/ru/>

## фейковый агрегатор {#pictures_47}

дисплей с агрегатором фейковых новостей на как бы серьёзных сайтах (всякая пропагандистская ерунда, газетные утки и т.д.) со всего интернета в одном месте. обновляется в реальном времени.

## музей числа π {#pictures_48}

cуществует предположение, что в числе $\pi$ содержится любая конечная последовательность цифр. если это действительно так, то в числе $\pi$ содержится любой из возможных файлов. выходит своеобразное воплощение идеи Вавилонской Библиотеки Борхеса.

даже если это не так, в этом числе всё равно много “интересных” последовательностей. почему бы не устроить из них музей?

__там (возможно) получится найти:__

- признание исследователя в любви своей девушке. его можно отправить, просто отправив смещение в числе $\pi$, где оно начинается и заканчивается;
- разнообразный вандализм: нецензурные надписи, увековеченные в математике;
- ответы на вечные вопросы человечества (необязательно правильные, но правильные там тоже будут!);
- разнообразную рекламу, которая и оплатит этот проект.

существует замечательная файловая система [$\pi$fs](https://github.com/philipl/pifs), которая хранит файлы в числе $\pi$. а ещё, если указанная гипотеза верна, то в числе $\pi$ есть бесконечно много программ, которые это число вычисляют, и вычисляющая его программа рано или поздно выведет свой код.

## старые тренды {#pictures_49}

стартап, состоящий в доставке смузи на дронах и гироскутерах.

## производство идеял {#pictures_50}

производство идеял: сотканных из идей одеял, которыми можно укрыться с головой от холодной и страшной реальности.

## выставка ретровирусов {#pictures_51}

ретро-компьютеры и вирусы под DOS, Amiga и пр.

## котбуки {#pictures_52}

гибриды нетбуков и котов: сами себя вылизывают (не нужно чистить от пыли) и засыпают на коленях.

## слэшер {#pictures_53}

слэшер о том, как Оккам борется с полчищем философских зомби своей бритвой.

## дикая кладь {#pictures_54}

дикая кладь и процесс её приручения.

## съезд крыш {#pictures_55}

ежегодные весенние и осенние съезды крыш: два раза в год на них съезжаются крыши со всего мира.

## жизненный тупик {#pictures_56}

человек стоит в жизненном тупике и лицезреет стену.

далее образуется сцена из "Космической Одиссеи 2001 года" Кубрика: он смотрит в этот тупик и говорит "My God, it's full of stars!"/

_это о том, как боль, страдание и кризисы могут дать серьёзное понимание мира._

## мозг из бюрократической машины (ex-machina) {#pictures_57}

попытка сымитировать человеческий мозг и личность с помощью огромного бюрократического аппарата.  

состоит из огромного здания, где за столами сидят люди ("нейроны"), а другие люди носят туда-сюда бумажки разных видов ("нейромедиаторы"), путешествуя с этажа на этаж.  

"нейроны" принимают бумажки, обрабатывают специальным образом, пишут новые и отправляют другим "нейронам".  

при этом личность, созданная таким образом, даже не подозревает о своей природе.

## геометрия мышления {#pictures_58}

- форма мыслей (их оформленность, их бесформенность);
- величина мысли (велика мысль или, наоборот, эта мысль мелкая);
- прикосновение/прилегание (смежность мыслей);
- расстояние друг от друга (близость мыслей);
- расположение "внутри" (напр. модель состоит из нескольких концепций, каждая из которых состоит из концепций поменьше);
- расположение "между" (мысль как переходная в цепочке размышлений);
- преобразования мыслей от одной до другой;
- инвариантность мыслей относительно преобразований;
- симметрии мыслей;
- угол между мыслями: насколько нужно повернуть своё мировоззрение, чтобы от одной мысли перейти к другой;
- линейная зависимость и независимость мыслей _(путь, как в песне ДДТ, очерчен прямой, человек зависим от других и даже помыслить не может свернуть с предначертанной прямой дорожки)_;
- ортогональность мыслей;
- многообразие мыслей;
- многомерность и одномерность ("евклидов ум мой" Достоевского);
- открытость мышления и замкнутость мышления;
- границы мышления, его ограниченность.

понятие __цвета мыслей__ (эмоциональная окраска: тёплые тона или холодные, к примеру) рассматривается отдельно от их геометрии.

## аннигиляционная любовь {#pictures_59}

любовь девушки из материи и парня из антиматерии.

## жизнь {#pictures_60}

**жизнь** -- это 

1. такой мужичок с фонариком в настоящем, освещающий будущее, который бредёт себе вперёд и собирает прошлое в мешочек, периодически рассыпая его, и теряя некоторые вещи.

    _некоторые вещи ломаются внутри от тряски (как воспоминания могут становиться другими со временем)._

2. геометрическая фигура в четырёхмерном пространстве.

## сардоническая улыбка {#pictures_61}

остров Сардиния, жители которого всегда ходят по улицам с сардонической улыбкой на лице (по аналогии с дежурной улыбкой у американцев).

## истина на дне (от)чая(ния) {#pictures_62}

истина на дне (от)__чая__(ния).

## машинное отделение Вселенной {#pictures_63}

**машинное отделение Вселенной** -- интереснейшее место! чего стоят хотя бы фонтаны, из которых цифра за цифрой льются иррациональные числа вроде $\pi$.

## патологоанатом-любитель {#pictures_64}

**патологоанатом-любитель** -- человек, понимающий, что для того, чтобы резать людей, иметь диплом совершенно необязательно.

## рай для идей {#pictures_65}

место, где цветут хорошие идеи, порой получая то, чего не получили в реальной жизни.

здесь полно вечных двигателей, оживших утопий, реализованных планов того, как сделать мир счастливым и так далее.

а вот чего тут нет, так это реальных людей -- вместо них есть только идеи-фантомы, ведь именно люди частенько и портят хорошие идеи, превращая их то в фарс, то в их полную противоположность.

## «споры» для мыслей и идей {#pictures_66}

как у бактерий, способ выжить в неблагоприятных условиях, чтобы позже реализоваться в благоприятных.

## создание поля вещественных чисел {#pictures_67}

1. сеем рациональное зерно;
2. выращиваем из зерна вещественные числа с помощью процедуры пополнения.

**альтернатива:** сделать множеству рациональных чисел дедекиндово сечение.

## танцпол {#pictures_68}

**танцпол** -- «обрезанная» стереографическая проекция сферы от диско-шара.

_а в честь сдачи экзамена по ТФКП мы устраиваем танцы на комплексной плоскости (как из диско-шара можно сделать танцпол силой математики)._

## тащиться за кем-то пледом {#pictures_69}

__тащиться за кем-то пледом__ -- о нежной и тёплой влюблённости.

## троллейбус, который идёт на Вудсток {#pictures_70}

троллейбус, который идёт на Вудсток!

## френдлента Мёбиуса {#pictures_71}

**френдлента Мёбиуса** -- бесконечно длинный список друзей.

## пикник у ненастроенного телевизора {#pictures_72}

**шум ненастроенного телевизора** -- это такой электромагнитный водопад (и там, и там волны). реликтовое излучение. электромагнитная гладь и волны.

пикник у ненастроенного телевизора -- это пикник у электромагнитного водопада.

## спины элементарных частиц {#pictures_73}

элементарные частицы очень любят, когда им чешут спины.
