# бестиарий {#beastie}

вымышленные существа. фрагменты книги [«сборник словарей»](https://abalompe.gitlab.io/dict/).

## Абаломпе {#abalompe}

хранитель Структуры, Формы, управляющий Метаморфозами, Деформациями, Преобразованиями.

весь Порядок (и, следовательно, вся несвобода) -- его сфера и ответственность. он -- персонификация всей математики и химии нашего мира, а также большей части искусства, кроме бесформенного -- ташизма, например.

## Безымянная {#unnamed}

Безымянная -- хранительница неоформленного, едва намеченного. её сфера -- сфера едва различимого, сфера зыбких фантазий ирреальности, где кое-где прорастают росточки существования.

в хаосе неоформленных явлений образуется нечто, что условно можно назвать игроками. они... будем считать, что они играют во что-то, что мы для удобства назовём "русской рулеткой". цена проигрыша здесь -- оформление проигравшего, его осуществление и выталкивание в реальность со всеми тяготами, присущими существованию.

время от времени в этом хаосе неоформленности образуются ещё большие островки сформированности.

один из них выглядит так: облако, на котором, привычно наплевав на законы вероятности, стоит хрущёвка. её жители -- обычные постсоветские люди обычных постсоветских типажей. они просто появились здесь в какой-то момент, весьма удивившись этому, и уж тем более удивительно для них то, что происходит вокруг. движение фантазии, образующей этот мир, зыбко, нестабильно, как и всё остальное, и время от времени хрущёвка дестабилизируется, исчезает на время и наполняется аномалиями вроде жирафа, высунувшего голову с балкона. седеющий толстяк в семейных трусах, открыв холодильник, чтобы достать оттуда банку пива, может с удивлением смотреть на вылетевших из холодильника бабочек.

эта игра увлекательна для пространства и населяющих его сущностей, интересна она и самой Безымянной, так что они готовы играть в неё снова и снова.

## Вселенский Пастух {#herdsman}

его Альдебараны, первичные бульоны, приготовленные из звёздной пыли, галактика как мясорубка и круговорот веществ в природе как мясорубка.

## Драматурги {#drama}

сверхъестественные существа, вмешивающиеся в (ранее благополучные) судьбы существ или целых миров, чтобы сделать из них цепляющую за живое эмоционально насыщенную историю, призванную удовлетворить их и Наблюдателей.

при этом они могут в каком-то смысле любить своих жертв/персонажей, как своих персонажей может любить писатель, позже их убивающий. и как раз тем, кого они любят больше всего, кто наиболее значим в Повествовании, они и создают наиболее серьёзные испытания.

полученные драмы могут быть учебными пособиями для других сверхъестественных существ.

## дегустаторы вин {#wine}

сверхъестественные существа, которые дегустируют разные виды вин(ы) перед тем, как вам кто-то навяжет выбранную ими вину.

## Ильсанори {#ilsanori}

это Пространство и это Время.

## Имитах {#imitah}

покровитель плагиатчиков и имитаторов, любителей делать всё по аналогии.

## Ингабека {#ongabeka}

священная собака, оставляющая лужи, в которых отражается небо, и помогающая понять, что даже в уродливом и пошлом можно увидеть великое.

## Ирмитья {#irmit}

её очень странная черта -- её любовь к мимикрии под различные природные процессы: шум водопада, дождь, шелест листьев, звон колокольчиков и безжизненную тишину необитаемых миров. она без малейшего затруднения может прикинуться ветром, причём так мастерски, что не каждый метеоролог отличил бы этот ветер от настоящего.

но самая удивительная её способность -- это способность вживаться в роль процессов, никогда до неё не существовавших: шёпот истекающих мгновений, лязг цепей смысла, звонкий смех жителей Чистых Земель и даже в сакральную роль поистине чистого звука, освобождённого и от слушателя, и от носителя.

## Исингера {#isingera}

существо с чувствительной и тёплой сутью, скрывающейся под панцирем жёсткости и темноты.

## Исиндала {#isindala}

дух Абстракции. редко покидает Платоновский мир идей. покровительница всех шизоидов.

## Истарг {#istarg}

__дух-перфекционист:__ цивилизации (прекрасные и сложные) появляются (порой на доли секунды) и сразу же исчезают, как только он видит в них недостаток. мечтает создать идеальную утопию, где все будут счастливы. беспощадно уничтожает цивилизации, где что-то пошло не так.

## мементомории {#memento}

существа, появляющиеся в жизни человека и предсказывающие скорую смерть. не они её причина и не им её отменять.

их роль в том, чтобы дать такому человеку переосмыслить жизнь, сделать нужные выводы. и они пытаются дать возможность поменять её, чтобы уж хоть и остаток жизни прожить как следует.

знание, что тебе и правда нечего терять даёт свободу. и это свобода -- и дар, и проклятье, которые могут дать тебе мементомории.

## мета-трикстеры (метафизические трикстеры) {#trick}

надмировые существа, играющие с обитателями вселенной шутки, злые или добрые.

«судьба сыграла с ним злую шутку» -- это именно их деятельность и ответственность. они обладают небольшой властью над миром, умея слегка отклонять судьбы и влиять на чьё-то поведение: для многих шуток этого вполне достаточно.

## метафизория (метаинфузория) {#metaphys}

простейшее (надмировое) метафизическое существо (биосфера трансцендентного и сакрального).

## метафорическая надстройка над миром {#metaphor}

если подняться на метафорический уровень и увидеть метафорическую надстройку над миром, можно увидеть существа-паучих, которые плетут паутину интриг, обволакивающих мир.

## мыслепуты {#muddle}

существа, запутывающие мысли; существа, помещающие мысли в путы.

## норковые мыслекрады {#mink_thoughts}

это такие маленькие существа, которые воруют мысли у тебя из-под носа и коллекционируют потом у себя в норках.

именно они виноваты в ситуациях, когда к тебе вот-вот придёт гениальное озарение, а потом внезапно "передумает". или когда ты забываешь, что только что хотел сказать (впрочем, иногда такие мысли удаётся вернуть специальным противомыслекрадным механизмам психики).

когда же удаётся найти их норку, среди разного мыслемусора порой удаётся отыскать настоящие шедевры. увы, сами мыслекрады не очень разборчивы.

## Озирости {#ozirosti}

существо, для обслуживания которого создан наш мир. оно питается обманутыми ожиданиями, прошедшими любвями, разочарованиями и прочим.

любовь, вдохновение, красота, утопии, мечты о лучшей жизни существуют лишь для того, чтобы быть в какой-то момент поломанными и пойти Озирости на корм.

самое вкусное блюдо для него -- уничтожение любимого объекта сильного и благородного человека, готового отдать свою жизнь, чтобы защитить этот объект.

## понимания {#understanding}

маленькие зверьки, которые больше всего на свете любят ускользать от и разыгрывать владельца, часто играя злые шутки.

## призраки {#ghosts}

ностальгия Вселенной по исчезнувшему объекту, её ожившие воспоминания о нём.

__аналогия:__ мы могли испытывать какое-то сильное чувство, например любовь, к кому-то или чему-то. само это чувство ушло, но вспоминая о нём, мы можем чувствовать ностальгию по этому чувству, и в каком-то неполном виде оно снова оживает.

## призраки-прокрастинаторы {#procrastination}

призраки, оставшиеся на Земле потому, что у них остались незаконченные дела, всё равно продолжающие при этом откладывать эти дела на потом.

## протозвуки {#sound}

существа-зачатки звуков, которые могут как зазвучать, так и слиться (добровольно или нет) с тишиной.

## протосмыслы {#sense}

существа-зачатки смыслов, которым ещё только предстоит стать бессмыслицей.

## радикколы {#radiccol}

раскалывают оболочки ощущений-впечатлений, и извлекают из них ядрышки звуков; ими и питаются.

## Сонали {#sonali}

редко плачет, но когда она плачет, она выплакивает целые Вселенные.

эта космологическая теория называется **"Большим Взрыдом"**.

## сдерживатели {#deterrent}

квазиразумные сущности, соответствующие некоторой (слишком опасной для реализации) идее. их деятельность заключается в том, чтобы мешать её осуществлению.

## Толкунаки {#tolkunak}

_ну а то, что в нашем безвременьи занимает место свободного времени, мы проводим, наблюдая сквозь гладь глубины жижи болота истинной природы реальности, избегая завихрений смысла и прочей странной ерунды, что время от времени образуется на поверхности моря житейского._

_кто придумал, что понятое становится прозрачным, нам решительно неведомо._

## Трансценденты {#transcendent}

ну что же, дорогие трансценденты, думаем, вас может заинтересовать одно из наших фирменных блюд: __салат из разных сортов пустот, собранных из разных сортов небытия.__

## чернобыльские белки {#squirrel}

умеют учиться на ошибках. узнавая о политических кризисах, затрагивающих ядерное вооружение, они начинают заготавливать чернобыльские ядерные жёлуди на ядерную зиму.

## Шибайоми {#shibayomi}

Начало, Ломка, Перестройка, Значение, Событие.

Ненависть мира, его гнев и боль.

## Шмиаоа {#shmiaoa}

покровительница заброшенных колодцев и шахт лифтов.

## Эвглена Прекрасная {#euglena}

прекраснейшая из протист.

увы, история осады Протистрои и прочие связанные с ней события известны лишь немногим из-за того ужасного пренебрежения, с которым люди относятся к простейшим.

## Юироа {#yuiroa}

мать Невозможного, дух парадоксов. реализовывалась через Эшера, Бертрана Рассела и многих других.
