# геометрия мышления {#geometry}

- форма мыслей (их оформленность, их бесформенность);
- величина мысли (велика мысль или, наоборот, эта мысль мелкая);
- прикосновение/прилегание (смежность мыслей);
- расстояние друг от друга (близость мыслей);
- расположение "внутри" (напр. модель состоит из нескольких концепций, каждая из которых состоит из концепций поменьше);
- расположение "между" (мысль как переходная в цепочке размышлений);
- преобразования мыслей от одной до другой;
- инвариантность мыслей относительно преобразований;
- симметрии мыслей;
- угол между мыслями\: насколько нужно повернуть своё мировоззрение, чтобы от одной мысли перейти к другой;
- линейная зависимость и независимость мыслей _(путь, как в песне ДДТ, очерчен прямой, человек зависим от других и даже помыслить не может свернуть с предначертанной прямой дорожки)_;
- ортогональность мыслей;
- многообразие мыслей;
- многомерность и одномерность ("евклидов ум мой" Достоевского);
- открытость мышления и замкнутость мышления;
- границы мышления, его ограниченность.

понятие __цвета мыслей__ (эмоциональная окраска\: тёплые тона или холодные, к примеру) рассматривается отдельно от их геометрии.
