--- 
title: "образы (книга без иллюстраций)"
author: "Павел Любецкий"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: article 
mainfont: "Noto Sans"
language: russian
description: "книга состоит из визуальных образов, которые можно нарисовать, но иллюстраций в ней нет."
---
# о книге {#about}

книга состоит из визуальных образов, которые можно нарисовать, но иллюстраций в ней нет.

__примеры:__

- дружелюбная, на скромная бездночка: очень стесняется, когда в неё всматриваются, у неё краснеют от этого щёки.
- портал в мир, где нет речи и словесного мышления. только солнце, звёзды и тишина.
- призраки погибших вселенных и угасших звёзд, у которых остались незаконченные дела.
- норковые шубы, вылазящие из своих нор и собирающиеся на охоту.
- норковые мыслекрады (такие маленькие существа, которые воруют мысли у тебя из-под носа и коллекционируют потом у себя в норках).
- мыслепуты (существа, запутывающие мысли, помещающие мысли в путы).
- путешествие между реальностями через белый шум различных телеканалов.
- песочные часы, в которых сыпется прах умирающего времени.
- навозные жуки, перекатывающие планеты из навоза по их орбитам.
- гибриды нетбуков и котов: сами себя вылизывают (не нужно чистить от пыли) и засыпают на коленях.
- старая чёрно-белая фотография огромного зала, где сидят десятки женщин-вычислительниц и вычисляют на бумаге хэши для майнинга первых биткоинов.
- идеяла (сотканные из идей одеяла, которыми можно укрыться с головой от холодной и страшной реальности).
- элементарные частицы, которые очень любят, когда им чешут спины.

__лицензия:__ [Creative Commons Attribution Share Alike 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.ru).
